print("Heloo world")
print("I am updating today")
print("I am creating a new branch")
print("to create a new branch is to have some configuration or code changes which needn't be put into the main(master) branch(repository")
print("I am adding this line to check if there will be a merge conflict")
print("this is a branch1 which is created from master branch")
